### ISSUE TITLE
not working properly in these kinda case

### ISSUE THREAD

**Issue by pixelperson6** [Invincible1996/flutter_tree#2]
{
      "parentId": 1,
      "value": "中华人民共和国",
      "id": 123
    },
    {
      "parentId": 1,
      "value": "上海市",
      "id": 12
    },
    {
      "parentId": 1,
      "value": "上海市",
      "id": 2
    },
    
    only the last item is shown

**Comment by Invincible1996** [comment]
invalidated json format.check it

**Comment by Invincible1996** [comment]
> { "parentId": 1, "value": "中华人民共和国", "id": 123 }, { "parentId": 1, "value": "上海市", "id": 12 }, { "parentId": 1, "value": "上海市", "id": 2 },
> 
> ```
> only the last item is shown 
> ```

invalidated json format.check it

**Comment by Invincible1996** [comment]
invalidated json format.check it
