### ISSUE TITLE
right to left

### ISSUE THREAD

**Issue by fakhravari** [Invincible1996/flutter_tree#3]
This mode is also added

**Comment by Invincible1996** [comment]
Please describe your needs in detail

**Comment by Invincible1996** [comment]
> This mode is also added

Please describe your needs in detail

**Comment by Invincible1996** [comment]
> This mode is also added

Please describe your needs in detail

**Comment by fakhravari** [comment]
hi
![Screenshot 2023-10-23 125607](https://github.com/Invincible1996/flutter_tree/assets/4311975/2d17bfab-f1f8-4c3d-a1b0-1a7d8e96015d)

**Comment by Invincible1996** [comment]
Please update to the latest version.Use isRTL property.

**Comment by Invincible1996** [comment]
ss

**Comment by fakhravari** [comment]
![vvvvvvvvvvv](https://github.com/Invincible1996/flutter_tree/assets/4311975/8a04cc55-39b5-4f8f-a7d7-f5602baf89ca)
Hello
How do I solve this problem?

**Comment by Invincible1996** [comment]
@fakhravari What's your flutter version?

**Comment by fakhravari** [comment]
> @fakhravari What's your flutter version?

Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (3 weeks ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3

**Comment by Invincible1996** [comment]
@fakhravari Try to update to the latest version. 3.22.2

**Comment by fakhravari** [comment]
> @fakhravari Try to update to the latest version. 3.22.2

The problem was solved with the latest version
Thankful

**Comment by fakhravari** [comment]
It shows only 1 level out of 3 levels
How should I fix it?
You can download the source in the link below
Thanks

https://biaupload.com/do.php?filename=org-52749f38afbf1.rar

![Screenshot 2024-06-12 154323](https://github.com/Invincible1996/flutter_tree/assets/4311975/12bff5c2-d21e-46d3-a9a2-8bab866d4037)

**Comment by Invincible1996** [comment]
@fakhravari Please update to the latest version.
