### ISSUE TITLE
called during build

### ISSUE THREAD

**Issue by fakhravari** [Invincible1996/flutter_tree#5]
setState() or markNeedsBuild() called during build.

https://github.com/Invincible1996/flutter_tree/assets/4311975/7bb89862-d635-4713-a217-e457bb0136e4

OnChecked events should not be fired when initialized

**Comment by fakhravari** [comment]
https://github.com/Invincible1996/flutter_tree/assets/4311975/c7102889-ae7a-4705-801c-263c0d6de5be

Why does it send a request 3 times with one click?

**Comment by Invincible1996** [comment]
@fakhravari please update to the latest version
