### ISSUE TITLE
tree结构的数据支持默认选中某个节点吗

### ISSUE THREAD

**Issue by zp-techie** [Invincible1996/flutter_tree#6]
tree结构的数据支持默认选中某个节点吗，怎么做呢

**Comment by Invincible1996** [comment]
@wangzhipeng-vicky 你是什么样的数据结构

**Comment by zp-techie** [comment]
`[
		{
			"children":[{
				"children":[{
					"children":[],
					"disabled":false,
					"id":-16,
					"label":"5555",
					"orgType":2,
					"pid":-12,
					"vehicleCount":null
				}],
				"disabled":false,
				"id":-12,
				"label":"test结算部",
				"orgType":2,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-10,
				"label":"接口测试部门（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-11,
				"label":"接口自动化部门（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[{
					"children":[],
					"disabled":false,
					"id":-15,
					"label":"维修二车间",
					"orgType":1,
					"pid":-13,
					"vehicleCount":null
				},{
					"children":[],
					"disabled":false,
					"id":-17,
					"label":"维修三车间",
					"orgType":2,
					"pid":-13,
					"vehicleCount":null
				},{
					"children":[],
					"disabled":false,
					"id":-14,
					"label":"维修一车间",
					"orgType":1,
					"pid":-13,
					"vehicleCount":null
				}],
				"disabled":false,
				"id":-13,
				"label":"青山维修厂",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-5,
				"label":"自动化结算部门（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-2,
				"label":"自动化结算订单（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-6,
				"label":"自动化结算订单单位计价（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-4,
				"label":"自动化结算业务单（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-7,
				"label":"自动化结算业务单单位计价（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-3,
				"label":"自动化结算运单（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-8,
				"label":"自动化结算运单实际车型阶梯计价（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			},{
				"children":[],
				"disabled":false,
				"id":-9,
				"label":"自动化结算运单预约车型阶梯计价（勿删）",
				"orgType":1,
				"pid":-1,
				"vehicleCount":null
			}],
			"disabled":false,
			"id":-1,
			"label":"项目自建",
			"orgType":1,
			"pid":0,
			"vehicleCount":null
		}
	]`
我想默认选中某个节点   比如下图

**Comment by zp-techie** [comment]
![image](https://github.com/Invincible1996/flutter_tree/assets/29621842/70cc0609-9807-407a-a263-1e72d28860c3)

**Comment by Invincible1996** [comment]
@wangzhipeng-vicky 支持这种结构的吧 你跑一下demo

**Comment by zp-techie** [comment]
是的 支持这种结构   我现在需要展示出来后默认选中一个节点  这个怎么做  另外你这个是多选的  如何设置只能单选

**Comment by Invincible1996** [comment]
@wangzhipeng-vicky 试试最新的版本
