### ISSUE TITLE
单选有问题

### ISSUE THREAD

**Issue by zp-techie** [Invincible1996/flutter_tree#7]
改坏了吧，
单选不会出现选中的样式，也不能选根节点

多选也 没有了readme上的样式：
 1、子节点有选中，父节点会是一种样式，权限中父节点会变成另外一种选中
 2、所有的子节点选中，父节点不会选中

**Comment by Invincible1996** [comment]
@wangzhipeng-vicky 有空我再研究下

**Comment by Invincible1996** [comment]
@wangzhipeng-vicky 1、单选只能选最小节点  单选如果是选根节点 那就没必要展示 根节点下面的字节点

**Comment by Invincible1996** [comment]
试试新版本
